name:                tinyjit-a64
version:             0.1.0.0
github:              "adamwespiser/tinyjit-a64"
author:              "Adam Wespiser"
maintainer:          "adamwespiser@gmail.com"
copyright:           "2020 Adam Wespiser"
license:             OtherLicense
description:         "A Tiny Just-In-Time compiler targetting the A64 instruction set architecture"

extra-source-files:
- README.md
- ChangeLog.md

default-extensions:
- BangPatterns
- OverloadedStrings
- TypeApplications

dependencies:
- base >= 4.7 && < 5
- text
- transformers
- unix
- vector

library:
  source-dirs: src


executables:
  tinyjit-a64-exe:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -rtsopts
    - -g
    - -dcore-lint
    - -debug
    dependencies:
    - tinyjit-a64

tests:
  tinyjit-a64-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tinyjit-a64
    - hspec

